
package eu.ubitech.ubicropper.gitproxy.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GitSOAPService", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GitSOAPService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFilesOfCommit", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.GetFilesOfCommit")
    @ResponseWrapper(localName = "getFilesOfCommitResponse", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.GetFilesOfCommitResponse")
    public List<String> getFilesOfCommit(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFilesBetweenTwoCommits", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.GetFilesBetweenTwoCommits")
    @ResponseWrapper(localName = "getFilesBetweenTwoCommitsResponse", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.GetFilesBetweenTwoCommitsResponse")
    public List<String> getFilesBetweenTwoCommits(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.EchoResponse")
    public String echo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveImage", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.SaveImage")
    @ResponseWrapper(localName = "saveImageResponse", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.SaveImageResponse")
    public boolean saveImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllRevisions", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.GetAllRevisions")
    @ResponseWrapper(localName = "getAllRevisionsResponse", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.GetAllRevisionsResponse")
    public List<String> getAllRevisions(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLatestRevision", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.GetLatestRevision")
    @ResponseWrapper(localName = "getLatestRevisionResponse", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.GetLatestRevisionResponse")
    public String getLatestRevision(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveImageToCERIFBook", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.SaveImageToCERIFBook")
    @ResponseWrapper(localName = "saveImageToCERIFBookResponse", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.SaveImageToCERIFBookResponse")
    public boolean saveImageToCERIFBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        byte[] arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteImage", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.DeleteImage")
    @ResponseWrapper(localName = "deleteImageResponse", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.DeleteImageResponse")
    public boolean deleteImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "manageTmpFolder", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.ManageTmpFolder")
    @ResponseWrapper(localName = "manageTmpFolderResponse", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.ManageTmpFolderResponse")
    public boolean manageTmpFolder(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImage", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.GetImage")
    @ResponseWrapper(localName = "getImageResponse", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.GetImageResponse")
    public byte[] getImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "initializeSIF4Province", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.InitializeSIF4Province")
    @ResponseWrapper(localName = "initializeSIF4ProvinceResponse", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", className = "eu.ubitech.ubicropper.gitproxy.service.InitializeSIF4ProvinceResponse")
    public boolean initializeSIF4Province(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
