
package eu.ubitech.ubicropper.gitproxy.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GitSOAPServiceService", targetNamespace = "http://services.gitproxy.ubicropper.ubitech.eu/", wsdlLocation = "file:/home/eleni/IdeaProjects/GitProxyModule/GitProxyClient/src/wsdl/GitProxy.wsdl")
public class GitSOAPServiceService
    extends Service
{

    private final static URL GITSOAPSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(eu.ubitech.ubicropper.gitproxy.service.GitSOAPServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = eu.ubitech.ubicropper.gitproxy.service.GitSOAPServiceService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/eleni/IdeaProjects/GitProxyModule/GitProxyClient/src/wsdl/GitProxy.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/eleni/IdeaProjects/GitProxyModule/GitProxyClient/src/wsdl/GitProxy.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GITSOAPSERVICESERVICE_WSDL_LOCATION = url;
    }

    public GitSOAPServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GitSOAPServiceService() {
        super(GITSOAPSERVICESERVICE_WSDL_LOCATION, new QName("http://services.gitproxy.ubicropper.ubitech.eu/", "GitSOAPServiceService"));
    }

    /**
     * 
     * @return
     *     returns GitSOAPService
     */
    @WebEndpoint(name = "GitSOAPServicePort")
    public GitSOAPService getGitSOAPServicePort() {
        return super.getPort(new QName("http://services.gitproxy.ubicropper.ubitech.eu/", "GitSOAPServicePort"), GitSOAPService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GitSOAPService
     */
    @WebEndpoint(name = "GitSOAPServicePort")
    public GitSOAPService getGitSOAPServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.gitproxy.ubicropper.ubitech.eu/", "GitSOAPServicePort"), GitSOAPService.class, features);
    }

}
